title: Antoine Cotten
author: Antoine Cotten
description: My personal web page. Perspectives on tech and whatnot.
url: https://acotten.com
og_image: /assets/img/site-pic.webp

header:
  pages:
    - name: Journal
      slug: /
    - name: Freelance
    - name: Software
    - name: About

footer:
  contact:
    - name: Email
      value: hello@acotten.com
      link: mailto:hello@acotten.com
  follow:
    - name: X
      link: https://x.com/antnco
      value: '@antnco'
    - name: LinkedIn
      link: https://linkedin.com/in/antoineco
      value: antoineco
    - name: GitHub
      link: https://github.com/antoineco
      value: antoineco
    - name: RSS
      link: /feed.xml

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE*.txt
  - CNAME
  - flake.*

plugins:
  - jekyll-feed
  - jekyll-sitemap

feed:
  excerpt_only: true
