# Site settings
# See default settings at https://jekyllrb.com/docs/configuration/#default-configuration
title: Antoine Cotten
description: IT Operations in a service-oriented world
url: https://acotten.com
permalink: post/:title

# Plugins
plugins:
  - jekyll-paginate
paginate: 5

# Exclusions
exclude:
  - README.md
  - LICENSE
  - assets/scss/
  - node_modules/
  - package*.json
  - Gemfile*
  - gulpfile.js

# Analytics
google_analytics: UA-77121622-1

# Custom variables
author: Antoine Cotten

navigation:
  - title: Home
    url: /
  - title: About
    url: /about

social:
  github: antoineco
  twitter: AntoineCotten
  linkedin: antoinecotten
